# Generated by Django 6.0.5 on 2026-05-21 22:21

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AwesomeList",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("uuid", models.UUIDField(default=uuid.uuid4, editable=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=255)),
                ("slug", models.SlugField(max_length=255, unique=True)),
                (
                    "source_url",
                    models.URLField(help_text="GitHub awesome-list repo URL", unique=True),
                ),
                ("repo_full_name", models.CharField(blank=True, default="", max_length=255)),
                ("description", models.TextField(blank=True, default="")),
                ("is_active", models.BooleanField(default=True)),
                ("last_scanned_at", models.DateTimeField(blank=True, null=True)),
                ("last_error", models.TextField(blank=True, default="")),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Repository",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("uuid", models.UUIDField(default=uuid.uuid4, editable=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("host", models.CharField(default="github", max_length=50)),
                ("full_name", models.CharField(max_length=255, unique=True)),
                ("owner", models.CharField(max_length=255)),
                ("name", models.CharField(max_length=255)),
                ("url", models.URLField(unique=True)),
                ("description", models.TextField(blank=True, default="")),
                ("homepage_url", models.URLField(blank=True, default="")),
                ("language", models.CharField(blank=True, default="", max_length=100)),
                ("license_name", models.CharField(blank=True, default="", max_length=255)),
                ("topics", models.JSONField(blank=True, default=list)),
                ("stars", models.PositiveIntegerField(default=0)),
                ("forks", models.PositiveIntegerField(default=0)),
                ("open_issues", models.PositiveIntegerField(default=0)),
                ("watchers", models.PositiveIntegerField(default=0)),
                ("default_branch", models.CharField(blank=True, default="", max_length=255)),
                ("is_archived", models.BooleanField(default=False)),
                ("is_disabled", models.BooleanField(default=False)),
                ("is_fork", models.BooleanField(default=False)),
                ("github_created_at", models.DateTimeField(blank=True, null=True)),
                ("github_updated_at", models.DateTimeField(blank=True, null=True)),
                ("github_pushed_at", models.DateTimeField(blank=True, null=True)),
                ("last_synced_at", models.DateTimeField(blank=True, null=True)),
                ("raw", models.JSONField(blank=True, default=dict)),
            ],
            options={
                "ordering": ["-stars", "full_name"],
                "indexes": [
                    models.Index(fields=["-stars"], name="repos_repos_stars_8185c3_idx"),
                    models.Index(
                        fields=["-github_pushed_at"], name="repos_repos_github__530f16_idx"
                    ),
                    models.Index(fields=["is_archived"], name="repos_repos_is_arch_0b5fa8_idx"),
                    models.Index(fields=["language"], name="repos_repos_languag_48bb44_idx"),
                ],
            },
        ),
        migrations.CreateModel(
            name="AwesomeListItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("uuid", models.UUIDField(default=uuid.uuid4, editable=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("first_seen_in_scan_at", models.DateTimeField(auto_now_add=True)),
                (
                    "awesome_list",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="repos.awesomelist",
                    ),
                ),
                (
                    "repository",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="awesome_items",
                        to="repos.repository",
                    ),
                ),
            ],
            options={
                "ordering": ["awesome_list__name", "repository__full_name"],
                "unique_together": {("awesome_list", "repository")},
            },
        ),
    ]
