# Generated by Django 6.0.5 on 2026-05-22 10:55

import uuid

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("repos", "0002_schedule_daily_missing_repo_sync"),
    ]

    operations = [
        migrations.CreateModel(
            name="RepositorySnapshot",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("uuid", models.UUIDField(default=uuid.uuid4, editable=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("captured_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("source", models.CharField(default="github_api", max_length=50)),
                ("description", models.TextField(blank=True, default="")),
                ("homepage_url", models.URLField(blank=True, default="")),
                ("language", models.CharField(blank=True, default="", max_length=100)),
                ("license_name", models.CharField(blank=True, default="", max_length=255)),
                ("topics", models.JSONField(blank=True, default=list)),
                ("stars", models.PositiveIntegerField(default=0)),
                ("forks", models.PositiveIntegerField(default=0)),
                ("open_issues", models.PositiveIntegerField(default=0)),
                ("watchers", models.PositiveIntegerField(default=0)),
                ("default_branch", models.CharField(blank=True, default="", max_length=255)),
                ("is_archived", models.BooleanField(default=False)),
                ("is_disabled", models.BooleanField(default=False)),
                ("is_fork", models.BooleanField(default=False)),
                ("github_created_at", models.DateTimeField(blank=True, null=True)),
                ("github_updated_at", models.DateTimeField(blank=True, null=True)),
                ("github_pushed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "repository",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="snapshots",
                        to="repos.repository",
                    ),
                ),
            ],
            options={
                "ordering": ["-captured_at", "-id"],
                "indexes": [
                    models.Index(
                        fields=["repository", "-captured_at"], name="repos_repos_reposit_d21cdd_idx"
                    ),
                    models.Index(fields=["-captured_at"], name="repos_repos_capture_14bad3_idx"),
                ],
            },
        ),
    ]
