# Generated by Django 6.0.5 on 2026-05-22 10:56

import uuid

import django.db.models.deletion
import pgvector.django.indexes
import pgvector.django.vector
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0001_enable_extensions"),
        ("repos", "0004_repositorysnapshot"),
    ]

    operations = [
        migrations.CreateModel(
            name="RepositoryEmbedding",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("uuid", models.UUIDField(default=uuid.uuid4, editable=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("model", models.CharField(max_length=255)),
                ("dimensions", models.PositiveSmallIntegerField(default=1536)),
                ("source_text_hash", models.CharField(max_length=64)),
                ("source_text_chars", models.PositiveIntegerField(default=0)),
                ("embedding", pgvector.django.vector.VectorField(dimensions=1536)),
                ("embedded_at", models.DateTimeField()),
                (
                    "repository",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="vector",
                        to="repos.repository",
                    ),
                ),
            ],
            options={
                "ordering": ["repository__full_name"],
                "indexes": [
                    models.Index(
                        fields=["model", "source_text_hash"], name="repo_emb_model_hash_idx"
                    ),
                    pgvector.django.indexes.HnswIndex(
                        ef_construction=64,
                        fields=["embedding"],
                        m=16,
                        name="repo_emb_vec_hnsw_idx",
                        opclasses=["vector_cosine_ops"],
                    ),
                ],
            },
        ),
    ]
