# Generated by Django 6.0.5 on 2026-05-22 13:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("repos", "0005_repositoryembedding"),
    ]

    operations = [
        migrations.AddField(
            model_name="repository",
            name="readme",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="repository",
            name="readme_last_error",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="repository",
            name="readme_path",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
        migrations.AddField(
            model_name="repository",
            name="readme_synced_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="repository",
            name="readme_url",
            field=models.URLField(blank=True, default="", max_length=500),
        ),
    ]
