# Generated by Django 6.0.5 on 2026-05-22 15:24

import django.contrib.postgres.indexes
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("repos", "0006_repository_readme_repository_readme_last_error_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="repository",
            name="generated_tags",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name="repository",
            name="generated_tags_last_error",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="repository",
            name="generated_tags_model",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
        migrations.AddField(
            model_name="repository",
            name="generated_tags_source_hash",
            field=models.CharField(blank=True, default="", max_length=64),
        ),
        migrations.AddField(
            model_name="repository",
            name="generated_tags_synced_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddIndex(
            model_name="repository",
            index=django.contrib.postgres.indexes.GinIndex(
                fields=["topics"], name="repo_topics_gin_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="repository",
            index=django.contrib.postgres.indexes.GinIndex(
                fields=["generated_tags"], name="repo_gen_tags_gin_idx"
            ),
        ),
    ]
