# Generated by Django 6.0.5 on 2026-05-22 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repos', '0007_repository_generated_tags_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='awesomelist',
            name='commits_count',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='awesomelist',
            name='default_branch',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='awesomelist',
            name='forks',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='awesomelist',
            name='github_created_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='awesomelist',
            name='github_pushed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='awesomelist',
            name='github_updated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='awesomelist',
            name='is_archived',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='awesomelist',
            name='is_disabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='awesomelist',
            name='open_issues',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='awesomelist',
            name='raw',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='awesomelist',
            name='readme_repository_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='awesomelist',
            name='stars',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='awesomelist',
            name='topics',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='awesomelist',
            name='watchers',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddIndex(
            model_name='awesomelist',
            index=models.Index(fields=['-stars'], name='repos_aweso_stars_b89ecb_idx'),
        ),
        migrations.AddIndex(
            model_name='awesomelist',
            index=models.Index(fields=['-github_pushed_at'], name='repos_aweso_github__a129d1_idx'),
        ),
        migrations.AddIndex(
            model_name='awesomelist',
            index=models.Index(fields=['-last_scanned_at'], name='repos_aweso_last_sc_18aa3d_idx'),
        ),
    ]
