# Generated by Django 6.0.5 on 2026-05-22 16:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("repos", "0007_repository_generated_tags_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="repository",
            name="ai_development_signals",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name="repository",
            name="uses_ai_for_development",
            field=models.BooleanField(default=False),
        ),
        migrations.AddIndex(
            model_name="repository",
            index=models.Index(
                fields=["uses_ai_for_development"], name="repos_repos_uses_ai_a02192_idx"
            ),
        ),
    ]
