# Generated by Django 6.0.5 on 2026-05-22 16:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("repos", "0009_merge_20260522_awesome_list_activity_and_daily_refresh"),
    ]

    operations = [
        migrations.AddField(
            model_name="repository",
            name="commit_count",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="repositorysnapshot",
            name="commit_count",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
