# Generated by Django 6.0.5 on 2026-05-23 06:45

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("repos", "0011_merge_ai_development_signals"),
    ]

    operations = [
        migrations.CreateModel(
            name="AwesomeListRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("uuid", models.UUIDField(default=uuid.uuid4, editable=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("source_url", models.URLField(help_text="GitHub awesome-list repo URL")),
                ("repo_full_name", models.CharField(max_length=255, unique=True)),
                ("requester_email", models.EmailField(blank=True, default="", max_length=254)),
                ("note", models.TextField(blank=True, default="")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("added", "Added"),
                            ("declined", "Declined"),
                        ],
                        db_index=True,
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("reviewed_at", models.DateTimeField(blank=True, null=True)),
                ("reviewer_notes", models.TextField(blank=True, default="")),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["status", "-created_at"], name="repos_aweso_status_cb415b_idx"
                    )
                ],
            },
        ),
    ]
