# Generated by Django 6.0.5 on 2026-05-25 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repos', '0012_awesome_list_request'),
    ]

    operations = [
        migrations.AddField(
            model_name='awesomelist',
            name='first_commit_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='repository',
            name='first_commit_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='repositorysnapshot',
            name='first_commit_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddIndex(
            model_name='awesomelist',
            index=models.Index(fields=['first_commit_at'], name='repos_aweso_first_c_97b8e4_idx'),
        ),
        migrations.AddIndex(
            model_name='repository',
            index=models.Index(fields=['first_commit_at'], name='repos_repos_first_c_4d0114_idx'),
        ),
    ]
