# Generated by Django 6.0.5 on 2026-06-01 21:15

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

import apps.repos.models


class Migration(migrations.Migration):

    dependencies = [
        ('repos', '0018_merge_repository_tag_backfill_and_starred_import'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NewsletterIssueDelivery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('recipient_email', models.EmailField(max_length=254)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('last_error', models.TextField(blank=True, default='')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='NewsletterSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('email', models.EmailField(max_length=254)),
                ('cadence', models.CharField(choices=[('weekly', 'Weekly'), ('monthly', 'Monthly')], db_index=True, default='weekly', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('unsubscribed_at', models.DateTimeField(blank=True, null=True)),
                ('unsubscribe_token', models.CharField(default=apps.repos.models.generate_newsletter_token, max_length=64, unique=True)),
            ],
            options={
                'ordering': ['repository__full_name', 'user_id'],
            },
        ),
        migrations.CreateModel(
            name='RepositoryCommit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('sha', models.CharField(max_length=64)),
                ('branch', models.CharField(blank=True, default='', max_length=255)),
                ('message', models.TextField(blank=True, default='')),
                ('html_url', models.URLField(blank=True, default='', max_length=500)),
                ('api_url', models.URLField(blank=True, default='', max_length=500)),
                ('author_name', models.CharField(blank=True, default='', max_length=255)),
                ('author_email', models.EmailField(blank=True, default='', max_length=254)),
                ('author_login', models.CharField(blank=True, default='', max_length=255)),
                ('authored_at', models.DateTimeField(blank=True, null=True)),
                ('committer_name', models.CharField(blank=True, default='', max_length=255)),
                ('committer_email', models.EmailField(blank=True, default='', max_length=254)),
                ('committer_login', models.CharField(blank=True, default='', max_length=255)),
                ('committed_at', models.DateTimeField(blank=True, null=True)),
                ('parent_shas', models.JSONField(blank=True, default=list)),
                ('additions', models.PositiveIntegerField(default=0)),
                ('deletions', models.PositiveIntegerField(default=0)),
                ('changed_files', models.PositiveIntegerField(default=0)),
                ('files', models.JSONField(blank=True, default=list)),
                ('patch_truncated', models.BooleanField(default=False)),
                ('raw_metadata', models.JSONField(blank=True, default=dict)),
                ('summary', models.TextField(blank=True, default='')),
                ('summary_model', models.CharField(blank=True, default='', max_length=255)),
                ('summary_source_hash', models.CharField(blank=True, default='', max_length=64)),
                ('summarized_at', models.DateTimeField(blank=True, null=True)),
                ('summary_last_error', models.TextField(blank=True, default='')),
            ],
            options={
                'ordering': ['-committed_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='RepositoryNewsletterIssue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cadence', models.CharField(choices=[('weekly', 'Weekly'), ('monthly', 'Monthly')], db_index=True, max_length=20)),
                ('period_start', models.DateField()),
                ('period_end', models.DateField()),
                ('slug', models.SlugField(max_length=120)),
                ('title', models.CharField(max_length=255)),
                ('content_markdown', models.TextField(blank=True, default='')),
                ('content_html', models.TextField(blank=True, default='')),
                ('commit_count', models.PositiveIntegerField(default=0)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('generation_model', models.CharField(blank=True, default='', max_length=255)),
                ('generation_source_hash', models.CharField(blank=True, default='', max_length=64)),
                ('generated_at', models.DateTimeField(blank=True, null=True)),
                ('generation_last_error', models.TextField(blank=True, default='')),
            ],
            options={
                'ordering': ['-period_start', 'repository__full_name'],
            },
        ),
        migrations.AddField(
            model_name='repository',
            name='newsletter_tracking_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='repository',
            name='newsletter_tracking_last_error',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='repository',
            name='newsletter_tracking_last_polled_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='repository',
            name='newsletter_tracking_started_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddIndex(
            model_name='repository',
            index=models.Index(fields=['newsletter_tracking_enabled', 'full_name'], name='repos_repos_newslet_c3a2fd_idx'),
        ),
        migrations.AddField(
            model_name='newslettersubscription',
            name='repository',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='newsletter_subscriptions', to='repos.repository'),
        ),
        migrations.AddField(
            model_name='newslettersubscription',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='newsletter_subscriptions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='newsletterissuedelivery',
            name='subscription',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deliveries', to='repos.newslettersubscription'),
        ),
        migrations.AddField(
            model_name='repositorycommit',
            name='repository',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='newsletter_commits', to='repos.repository'),
        ),
        migrations.AddField(
            model_name='repositorynewsletterissue',
            name='repository',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='newsletter_issues', to='repos.repository'),
        ),
        migrations.AddField(
            model_name='newsletterissuedelivery',
            name='issue',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deliveries', to='repos.repositorynewsletterissue'),
        ),
        migrations.AddIndex(
            model_name='newslettersubscription',
            index=models.Index(fields=['repository', 'cadence', 'is_active'], name='repos_newsl_reposit_2ecd95_idx'),
        ),
        migrations.AddIndex(
            model_name='newslettersubscription',
            index=models.Index(fields=['user', 'is_active'], name='repos_newsl_user_id_495926_idx'),
        ),
        migrations.AddConstraint(
            model_name='newslettersubscription',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('user', 'repository'), name='unique_active_newsletter_subscription'),
        ),
        migrations.AddIndex(
            model_name='repositorycommit',
            index=models.Index(fields=['repository', '-committed_at'], name='repos_repos_reposit_77370b_idx'),
        ),
        migrations.AddIndex(
            model_name='repositorycommit',
            index=models.Index(fields=['branch', '-committed_at'], name='repos_repos_branch_2e84e3_idx'),
        ),
        migrations.AddIndex(
            model_name='repositorycommit',
            index=models.Index(fields=['summarized_at'], name='repos_repos_summari_6544f8_idx'),
        ),
        migrations.AddConstraint(
            model_name='repositorycommit',
            constraint=models.UniqueConstraint(fields=('repository', 'sha'), name='unique_repository_newsletter_commit'),
        ),
        migrations.AddIndex(
            model_name='repositorynewsletterissue',
            index=models.Index(fields=['repository', 'cadence', '-period_start'], name='repos_repos_reposit_b53f75_idx'),
        ),
        migrations.AddIndex(
            model_name='repositorynewsletterissue',
            index=models.Index(fields=['published_at'], name='repos_repos_publish_6a9ade_idx'),
        ),
        migrations.AddConstraint(
            model_name='repositorynewsletterissue',
            constraint=models.UniqueConstraint(fields=('repository', 'cadence', 'period_start'), name='unique_repository_newsletter_issue_period'),
        ),
        migrations.AddConstraint(
            model_name='repositorynewsletterissue',
            constraint=models.UniqueConstraint(fields=('repository', 'cadence', 'slug'), name='unique_repository_newsletter_issue_slug'),
        ),
        migrations.AddIndex(
            model_name='newsletterissuedelivery',
            index=models.Index(fields=['sent_at'], name='repos_newsl_sent_at_ccf088_idx'),
        ),
        migrations.AddIndex(
            model_name='newsletterissuedelivery',
            index=models.Index(fields=['recipient_email', '-created_at'], name='repos_newsl_recipie_41778f_idx'),
        ),
        migrations.AddConstraint(
            model_name='newsletterissuedelivery',
            constraint=models.UniqueConstraint(fields=('issue', 'subscription'), name='unique_newsletter_issue_delivery'),
        ),
    ]
