# Generated by Django 6.0.5 on 2026-06-01 21:50

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repos', '0019_repository_dependency_ecosystems_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AwesomeListSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('captured_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('source', models.CharField(default='github_api', max_length=50)),
                ('repo_full_name', models.CharField(blank=True, default='', max_length=255)),
                ('description', models.TextField(blank=True, default='')),
                ('topics', models.JSONField(blank=True, default=list)),
                ('stars', models.PositiveIntegerField(default=0)),
                ('forks', models.PositiveIntegerField(default=0)),
                ('open_issues', models.PositiveIntegerField(default=0)),
                ('watchers', models.PositiveIntegerField(default=0)),
                ('commits_count', models.PositiveIntegerField(blank=True, null=True)),
                ('readme_repository_count', models.PositiveIntegerField(default=0)),
                ('default_branch', models.CharField(blank=True, default='', max_length=255)),
                ('is_archived', models.BooleanField(default=False)),
                ('is_disabled', models.BooleanField(default=False)),
                ('github_created_at', models.DateTimeField(blank=True, null=True)),
                ('github_updated_at', models.DateTimeField(blank=True, null=True)),
                ('github_pushed_at', models.DateTimeField(blank=True, null=True)),
                ('first_commit_at', models.DateTimeField(blank=True, null=True)),
                ('awesome_list', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='snapshots', to='repos.awesomelist')),
            ],
            options={
                'ordering': ['-captured_at', '-id'],
                'indexes': [models.Index(fields=['awesome_list', '-captured_at'], name='repos_aweso_awesome_5764da_idx'), models.Index(fields=['-captured_at'], name='repos_aweso_capture_b77bde_idx')],
            },
        ),
    ]
