# Generated by Forge on 2026-06-02

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("repos", "0020_awesomelistsnapshot"),
        ("repos", "0020_schedule_repository_newsletters"),
    ]

    operations = []
