# Generated by Django 6.0.5 on 2026-06-08 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repos', '0021_merge_awesome_list_snapshots_and_repository_newsletters'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='repositorysnapshot',
            index=models.Index(fields=['repository', 'captured_at', 'id'], name='repo_snap_growth_idx'),
        ),
    ]
