# Generated by Django 6.0.5 on 2026-05-25 18:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="emailsent",
            name="email_type",
            field=models.CharField(
                choices=[("EMAIL_CONFIRMATION", "Email Confirmation"), ("WELCOME", "Welcome")],
                help_text="Type of email sent",
                max_length=50,
            ),
        ),
        migrations.DeleteModel(
            name="Feedback",
        ),
    ]
