# Generated by Django 6.0.5 on 2026-06-01 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_profile_github_starred_repos_import_enabled_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailsent',
            name='email_type',
            field=models.CharField(choices=[('EMAIL_CONFIRMATION', 'Email Confirmation'), ('NEWSLETTER', 'Newsletter'), ('WELCOME', 'Welcome')], help_text='Type of email sent', max_length=50),
        ),
    ]
