# Generated by Django 6.0.5 on 2026-06-01 21:05

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_profile_github_starred_repos_import_enabled_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SponsorAdPurchase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('stripe_checkout_session_id', models.CharField(max_length=255, unique=True)),
                ('stripe_payment_intent_id', models.CharField(blank=True, default='', max_length=255)),
                ('stripe_customer_id', models.CharField(blank=True, default='', max_length=255)),
                ('amount_total', models.PositiveIntegerField(default=0)),
                ('currency', models.CharField(blank=True, default='usd', max_length=8)),
                ('buyer_email', models.EmailField(blank=True, default='', max_length=254)),
                ('buyer_name', models.CharField(blank=True, default='', max_length=255)),
                ('status', models.CharField(choices=[('checkout_started', 'Checkout started'), ('paid', 'Paid'), ('active', 'Active')], default='checkout_started', max_length=32)),
                ('notification_sent_at', models.DateTimeField(blank=True, null=True)),
                ('details_submitted_at', models.DateTimeField(blank=True, null=True)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='sponsor-ads/logos/')),
                ('startup_name', models.CharField(blank=True, default='', max_length=120)),
                ('short_description', models.CharField(blank=True, default='', max_length=180)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
