# Generated by Django 6.0.5 on 2026-06-01 22:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0005_alter_emailsent_email_type"),
        ("core", "0005_sponsoradpurchase"),
    ]

    operations = []
