# Generated by Django 6.0.5 on 2026-06-02 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_highlighted_repo_purchase'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='remove_ads',
            field=models.BooleanField(default=False),
        ),
    ]
